# Homework 2.3 [SOLO]: Microtubule catastrophe and ECDFs (30 pts) - Adiel Perez

a) Write a function with the call signature ecdfvals(data), which takes a one-dimensional Numpy array (or Pandas Series; the same construction of your function will work for both) of data and returns the x and y values for plotting the ECDF in the “dots” style, as in Fig. 2a of the Gardner, Zanic, et al. paper. As a reminder,

ECDF(x) = fraction of data points ≤ x.

When you write this function, you may only use base Python and the standard library, in addition to Numpy and Pandas.

In [14]:
import numpy as np # array manipulation
import pandas as pd # data manipulation
import bokeh.io
import bokeh.plotting
bokeh.io.output_notebook()

Loading BokehJS ...

In [15]:
pwd

'/Users/adielperez/11-bebi103a-2021/lesson_exercises'

In [16]:
# Upload data as 'data'
data = pd.read_csv('gardner_time_to_catastrophe_dic_tidy.csv')

In [17]:
data

Unnamed: 0  time to catastrophe (s)  labeled
0             0                    470.0     True
1             1                   1415.0     True
2             2                    130.0     True
3             3                    280.0     True
4             4                    550.0     True
..          ...                      ...      ...
301         301                    180.0    False
302         302                    145.0    False
303         303                    745.0    False
304         304                    390.0    False
305         305                   1410.0    False

[306 rows x 3 columns]

In [18]:
unlabeled = data.loc[data['labeled'] == True]
unlabeled

Unnamed: 0  time to catastrophe (s)  labeled
0             0                    470.0     True
1             1                   1415.0     True
2             2                    130.0     True
3             3                    280.0     True
4             4                    550.0     True
..          ...                      ...      ...
206         206                    195.0     True
207         207                    705.0     True
208         208                    300.0     True
209         209                    605.0     True
210         210                    600.0     True

[211 rows x 3 columns]

In [19]:
labeled = data.loc[data['labeled'] == False]
labeled

Unnamed: 0  time to catastrophe (s)  labeled
211         211                    355.0    False
212         212                    425.0    False
213         213                    540.0    False
214         214                    265.0    False
215         215                   1815.0    False
..          ...                      ...      ...
301         301                    180.0    False
302         302                    145.0    False
303         303                    745.0    False
304         304                    390.0    False
305         305                   1410.0    False

[95 rows x 3 columns]

In [20]:
#define ecdf function into return x and y
def ecdf(data):
    x = np.sort(data)
    y = np.arange(1,len(data)+1)/len(data)
    return (x, y) 

In [21]:
unlabeled_x = ecdf(unlabeled["time to catastrophe (s)"])[0]
unlabeled_x

array([  55.,   60.,   65.,   65.,   75.,   80.,   80.,   95.,   95.,
        100.,  105.,  105.,  115.,  120.,  120.,  120.,  130.,  130.,
        135.,  135.,  135.,  135.,  140.,  140.,  150.,  155.,  155.,
        155.,  155.,  155.,  170.,  170.,  180.,  180.,  180.,  180.,
        185.,  185.,  185.,  190.,  190.,  190.,  195.,  195.,  200.,
        200.,  205.,  210.,  210.,  215.,  215.,  220.,  220.,  225.,
        225.,  225.,  225.,  235.,  240.,  240.,  245.,  245.,  245.,
        250.,  255.,  255.,  260.,  270.,  270.,  270.,  275.,  280.,
        280.,  280.,  280.,  280.,  285.,  285.,  285.,  290.,  290.,
        290.,  290.,  290.,  295.,  300.,  305.,  305.,  320.,  320.,
        325.,  325.,  330.,  330.,  340.,  340.,  340.,  340.,  340.,
        345.,  345.,  350.,  360.,  360.,  365.,  365.,  370.,  370.,
        370.,  380.,  380.,  385.,  385.,  390.,  390.,  395.,  395.,
        400.,  400.,  410.,  415.,  415.,  420.,  425.,  435.,  440.,
        440.,  445.,

In [22]:
unlabeled_y = ecdf(unlabeled["time to catastrophe (s)"])[1]
unlabeled_y

array([0.00473934, 0.00947867, 0.01421801, 0.01895735, 0.02369668,
       0.02843602, 0.03317536, 0.03791469, 0.04265403, 0.04739336,
       0.0521327 , 0.05687204, 0.06161137, 0.06635071, 0.07109005,
       0.07582938, 0.08056872, 0.08530806, 0.09004739, 0.09478673,
       0.09952607, 0.1042654 , 0.10900474, 0.11374408, 0.11848341,
       0.12322275, 0.12796209, 0.13270142, 0.13744076, 0.14218009,
       0.14691943, 0.15165877, 0.1563981 , 0.16113744, 0.16587678,
       0.17061611, 0.17535545, 0.18009479, 0.18483412, 0.18957346,
       0.1943128 , 0.19905213, 0.20379147, 0.20853081, 0.21327014,
       0.21800948, 0.22274882, 0.22748815, 0.23222749, 0.23696682,
       0.24170616, 0.2464455 , 0.25118483, 0.25592417, 0.26066351,
       0.26540284, 0.27014218, 0.27488152, 0.27962085, 0.28436019,
       0.28909953, 0.29383886, 0.2985782 , 0.30331754, 0.30805687,
       0.31279621, 0.31753555, 0.32227488, 0.32701422, 0.33175355,
       0.33649289, 0.34123223, 0.34597156, 0.3507109 , 0.35545

In [23]:
labeled_x = ecdf(labeled["time to catastrophe (s)"])[0]
labeled_x

array([  40.,   60.,   75.,   80.,   85.,   85.,  125.,  125.,  130.,
        130.,  135.,  140.,  145.,  145.,  145.,  150.,  155.,  155.,
        160.,  160.,  165.,  170.,  180.,  180.,  180.,  180.,  190.,
        195.,  210.,  215.,  235.,  235.,  235.,  245.,  250.,  265.,
        265.,  280.,  295.,  305.,  305.,  320.,  330.,  335.,  350.,
        355.,  355.,  360.,  370.,  370.,  380.,  390.,  395.,  400.,
        405.,  405.,  410.,  415.,  420.,  420.,  425.,  445.,  445.,
        460.,  460.,  460.,  490.,  495.,  500.,  505.,  510.,  525.,
        525.,  540.,  540.,  575.,  600.,  615.,  640.,  660.,  670.,
        695.,  700.,  735.,  745.,  750.,  765.,  770.,  870.,  950.,
       1110., 1145., 1255., 1410., 1815.])

In [24]:
labeled_y = ecdf(labeled["time to catastrophe (s)"])[1]
labeled_y 

array([0.01052632, 0.02105263, 0.03157895, 0.04210526, 0.05263158,
       0.06315789, 0.07368421, 0.08421053, 0.09473684, 0.10526316,
       0.11578947, 0.12631579, 0.13684211, 0.14736842, 0.15789474,
       0.16842105, 0.17894737, 0.18947368, 0.2       , 0.21052632,
       0.22105263, 0.23157895, 0.24210526, 0.25263158, 0.26315789,
       0.27368421, 0.28421053, 0.29473684, 0.30526316, 0.31578947,
       0.32631579, 0.33684211, 0.34736842, 0.35789474, 0.36842105,
       0.37894737, 0.38947368, 0.4       , 0.41052632, 0.42105263,
       0.43157895, 0.44210526, 0.45263158, 0.46315789, 0.47368421,
       0.48421053, 0.49473684, 0.50526316, 0.51578947, 0.52631579,
       0.53684211, 0.54736842, 0.55789474, 0.56842105, 0.57894737,
       0.58947368, 0.6       , 0.61052632, 0.62105263, 0.63157895,
       0.64210526, 0.65263158, 0.66315789, 0.67368421, 0.68421053,
       0.69473684, 0.70526316, 0.71578947, 0.72631579, 0.73684211,
       0.74736842, 0.75789474, 0.76842105, 0.77894737, 0.78947

In [31]:
# Plotting instructions 
p = bokeh.plotting.figure(frame_height=400,
    frame_width=600,
    x_axis_label='Time of Catastrophe (s)',
    y_axis_label='ECDF', title='Microtubule Catastrophe')

# Instructing to include unlabeled ecdf data in plot
p.circle(unlabeled_x, 
         unlabeled_y, 
         color="purple",
         legend_label="unlabeled",)

# Instructing to include labeled ecdf data in plot
p.circle(labeled_x, 
         labeled_y,
         color="green",
         legend_label="labeled",)

p.legend.location = 'bottom_right'

bokeh.io.show(p)

In [30]:
# Graph plotted with labeled as the green curve and unlabeled as the purple curve. 

In [26]:
%load_ext watermark
%watermark -v -p numpy,pandas,bokeh,jupyterlab

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Python implementation: CPython
Python version       : 3.9.5
IPython version      : 7.27.0

numpy     : 1.20.3
pandas    : 1.3.2
bokeh     : 2.3.3
jupyterlab: 3.1.13



b) Question: Use the ecdfvals() function that you wrote to plot the ECDFs shown in Fig. 2a of the Gardner, Zanic, et al. paper. By looking this plot, do you think that the fluorescent labeling makes a difference in the onset of catastrophe? (We will do a more careful statistical inference later in the course, but for now, does it pass the eye test? Eye tests are an important part of EDA.) 

Response: There is little difference in fluorescent labeleing with the onset of catastrophe. However, the fluorescent labeled microtubele did have an earlier onset of catastrophe. It was most appartent at 0.7 ECDF were labeled microtubele underwent catastrophe at ~430s and the unlabeled microtubele underwent catastrophe at ~530s.