# Homework 6.1 [SOLO]: Marginalization by sampling (30 pts) - Adiel Perez


a) Draw 2,000 samples for $\mathbf{X} = (x_1, x_2, x_3)$
 out of a trivariate Normal distribution. You can refer to the Distribution Explorer for direction on how to do that. For your choice of parameters, use
 
 $\nu = \left[
\begin{array}{ccc}
10 & 15 & 25
\end{array}
\right]^{T}$
 
 $\Sigma = \left[\begin{array}{ccc}
6 & -7 & -5 \\
-7 & 13 & 11\\
-5 & 11 & 10
\end{array}\right]$

In [1]:
import numpy as np 
import scipy.stats
import scipy.linalg as spla
import bokeh.io
import pandas as pd
import iqplot
bokeh.io.output_notebook()

Loading BokehJS ...

In [2]:
def multivariate_normal_sampler(mean, covariance, n_samples=1):
    L = spla.cholesky(covariance)
    Z = np.random.normal(size=(n_samples, covariance.shape[0]))
    return Z.dot(L) + mean

In [3]:
x = [6, -7, -5]
y = [-7, 13,11]
z = [-5, 11, 10]
mean = np.array([10, 15, 25]).T
covariance = np.array([x, y, z])
X = multivariate_normal_sampler(mean, covariance, n_samples=2000)

In [4]:
X.mean(axis=0)

array([ 9.95697296, 15.05701663, 25.04235671])

In [5]:
np.cov(X.T)

array([[ 5.84471512, -6.88071196, -4.9010761 ],
       [-6.88071196, 12.79733267, 10.77631238],
       [-4.9010761 , 10.77631238,  9.75944643]])

In [6]:
# Set parameters
mu = 10
sigma = np.sqrt(6)
rg = np.random.default_rng()
# Draw 2000 random samples
x = rg.normal(mu, sigma, size=2000)

# Plot the histogram
p = iqplot.histogram(x, rug=False, density=True, y_axis_label="approximate PDF",)

bokeh.io.show(p)

In [16]:
X

array([[ 9.40263752, 13.60018559, 22.9023051 ],
       [10.75764884, 11.26492132, 20.62013864],
       [ 8.71588317, 13.58750527, 22.9320992 ],
       ...,
       [12.42877522, 12.15820361, 22.61509604],
       [10.54598945, 18.4106448 , 29.12839545],
       [ 9.8201953 , 19.09445483, 30.29907695]])

* The X array has three columns which represents $\mathbf{X} = (x_1, x_2, x_3)$ for each sample drawn, which is why we have two thousand rows. Therefore,* The X array has three columns which represents $\mathbf{X} = (x_1, x_2, x_3)$ for each sample drawn, which is why we have two thousand rows. Therefore, we drew 2,000 samples for $\mathbf{X} = (x_1, x_2, x_3)$ out of a trivariate Normal distribution.

In [18]:
Tran_X = np.transpose(X) #Need to transpose since we want to make three rows x1, x2, x3
Tran_X

array([[ 9.40263752, 10.75764884,  8.71588317, ..., 12.42877522,
        10.54598945,  9.8201953 ],
       [13.60018559, 11.26492132, 13.58750527, ..., 12.15820361,
        18.4106448 , 19.09445483],
       [22.9023051 , 20.62013864, 22.9320992 , ..., 22.61509604,
        29.12839545, 30.29907695]])

In [19]:
X1 = Tran_X[0] #We index 0 to isolate all the values in the first row which are all our x1 values. 
X1

array([ 9.40263752, 10.75764884,  8.71588317, ..., 12.42877522,
       10.54598945,  9.8201953 ])

In [20]:
# Compute theoretical CDF
x_theor = np.linspace(1, 18, 2000)
y_theor = scipy.stats.norm.cdf(x_theor, mu, sigma)

# Plot the ECDF of the 2000 x1 randomly generated numbers
p = iqplot.ecdf(X1, marker_kwargs={"fill_color": None},)

p.line(
    x=x_theor, y=y_theor, line_width=2, line_color="orange",
)

bokeh.io.show(p)

* Plot of the samples of $x_1$ overlaid with the CDF of the theoretical distribution for $f(x)$ match exactly!

In [13]:
%load_ext watermark
%watermark -v -p numpy,scipy,pandas,bokeh,iqplot,jupyterlab

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Python implementation: CPython
Python version       : 3.9.5
IPython version      : 7.27.0

numpy     : 1.20.3
scipy     : 1.7.1
pandas    : 1.3.2
bokeh     : 2.3.3
iqplot    : 0.2.3
jupyterlab: 3.1.13

